project:
  type: book

book:
  title: "Geospatial Technology and Spatial Analysis in R"
  author: 
    - Masumbuko Semba
    - Nyamisi Peter
    - Benjamini Mpinga
    
  date: "29/05/2023"
  chapters:
    - index.qmd
    - ch0.qmd
    - ch1.qmd
    - ch2.qmd
    - ch3.qmd
    - ch3Edition.qmd
    - ch4.qmd
    - ch41.qmd
    - ch5.qmd
    - ch6.qmd
    - ch7.qmd
    - ch8.qmd
    - ch9.qmd
    - ch10.qmd
    - ch11.qmd
    - ch12.qmd
    - ch13.qmd
    # - ch1.qmd
    # - ch1.qmd
    # - ch1.qmd
    # - ch1.qmd
    - references.qmd

bibliography: [references.bib]
linkcolor: "blue"
citecolor: "red"

format:
  html:
    theme: cosmo
    code-link: true
  pdf:
    documentclass: scrbook
  
crossref:
  fig-title: '**FIGURE**'
  fig-labels: arabic
  tbl-title: '**TABLE**'
  tbl-labels: arabic
  title-delim: "**.**"
execute: 
  eval: true
  echo: true
  warning: false
  message: ""
css: style.css
highlight-style: ayu-mirage
code-line-numbers: true
code-fold: show





